version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:22.13.0
    steps:
      - checkout

      - setup_remote_docker

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

      - run:
          name: Clean up previous install
          command: rm -rf node_modules
      
      - run:
          name: Set pnpm store directory
          command: |
            npm install pnpm
            npx pnpm config set store-dir .pnpm-store

      - run:
          name: Install dependencies
          command: npx pnpm install --no-frozen-lockfile

      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

      - run:
          name: Build the app
          command: npx pnpm build

      - run:
          name: Build Docker Image
          command: |
            TAG=$(TZ=Asia/Seoul date +'%y%m%d.%H%M%S')
            docker build -t chatflow/fe:1.0.0-$TAG .
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push chatflow/fe:1.0.0-$TAG

workflows:
  build_and_push_on_main:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main
