version: 2.1

jobs:
  build_and_push:
    docker:
      - image: cimg/node:22.2.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - run:
          name: Install pnpm
          command: corepack enable && pnpm install
      - run:
          name: Build the app
          command: pnpm build
      - run:
          name: Build Docker Image
          command: |
            TAG=$(TZ=Asia/Seoul date +'%y%m%d.%H%M%S')
            docker build -t chatflow/fe:1.0.0-$TAG .
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push chatflow/fe:1.0.0-$TAG
workflows:
  build_and_push_on_main:
    jobs:
      - build_and_push:
          filters:
            branches:
              only: main
